# Aula 02 - Python

## Dados Numéricos

In [37]:
# Variável inteira
a = 1
print(' Valor de a = '+str(a))
type(a)

 Valor de a = 1


int

A função print() é usada para exibir mensagens na saída padrão (normalmente, a tela do console).\ A função type() é usada para obter o tipo de um objeto em Python. Ela retorna o tipo de dados do objeto passado como argumento. Isso é útil para verificar tipos de variáveis, argumentos de função e retorno de função.

In [38]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [39]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [40]:
# Declarando NaN
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

NaN é frequentemente usado para representar resultados inválidos ou indeterminados em operações aritméticas. 

In [41]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


In [42]:
# Declaração de variável de texto
f = 'Bruna'
g = "Boscato"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Bruna
Boscato
BrunaBoscato
Bruna Boscato


## Dados tipo bool - lógica

In [43]:
a == 1 # perguntando se a é igual a 1

True

Tipo de dado booleano é representado pelos valores "True" e "False", que são usados para expressar verdadeiro e falso.

In [44]:
h = (a==1) # salvando o resultado de a==1 no h
print(h)
type(h)

True


bool

In [45]:
h = (a==2)
print(h)
type(h)

False


bool

In [46]:
i = True # salvando i como verdadeiro na forma booleana 
type(i)

bool

In [47]:
ii = 'True' # salvando ii como uma string
type(ii)

str

## Operação de comparação 

Refere-se a uma expressão que compara dois valores para determinar sua relação.

In [48]:
# Operação ==
a == b

True

Essas operações comparam valores e produzem um resultado booleano (verdadeiro ou falso) com base na relação entre eles.

In [49]:
# Operação ><
a>b

False

In [50]:
# Operação !=
a!=b # se a é diferente de b

False

In [51]:
# Operação >= ou <=
a>=b

True

## Operações matemáticas

In [52]:
# Soma
a+b

2.0

In [53]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [54]:
# Multiplicação
l = a*b # Não use l como variável 
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [55]:
# Divisão 
a/b

1.0

In [56]:
# Potência 
5**2

25

In [57]:
# Operações matemáticas com a biblioteca math
import math # importanto a biblioteca
math.exp(10)

22026.465794806718

"math" é uma biblioteca padrão que fornece funções e constantes matemáticas para operações mais avançadas do que aquelas disponíveis nos operadores aritméticos básicos, permitindo realizar uma ampla gama de operações matemáticas, desde funções trigonométricas até funções exponenciais e logarítmicas.

In [58]:
math.exp(0) # usando a biblioteca math para calcular a exponencial de 0

1.0

In [59]:
math.exp(a) # usando a biblioteca math para calcular a exponencial de a

2.718281828459045

In [60]:
math.exp(-10) # usando a biblioteca math para calcular a exponencial de -10

4.5399929762484854e-05

In [61]:
import math as mt # importando a biblioteca math e declarando como vou chama-la 
mt.log(c)

0.0

In [62]:
mt.log10(100) # usando a biblioteca math para calcular o logaritimo na base 10 de 100

2.0

## Listas

In [63]:
myFirstList = [1,2,3] # criando uma lista
print(myFirstList)

[1, 2, 3]


In [64]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


Da para acessar os valores de uma lista através do índice usando a sintaxe de colchetes ([]).

O índice é um número inteiro que representa a posição do elemento na lista. Lembrando de que o primeiro elemento da lista tem índice 0, o segundo tem índice 1 e assim por diante.

In [65]:
myFirstList==a # perguntando se a myFirstList é igual ao a

False

In [66]:
myFirstList[0]==a # perguntando se o primeiro valor de myFirstList é igual ao a

True

In [67]:
mySecList = [1,a,'c'] # fazendo a SecList com o primeiro número igual a 1, o segundo é referente ao a e o terceiro é uma string escrito c
print(mySecList)

[1, 1, 'c']


In [68]:
type(mySecList) # pedindo o tipo da lista

list

In [69]:
type(mySecList[2]) # pedindo o tipo do terceiro valor da lista

str

In [70]:
type(mySecList[1]) # pedindo o tipo do segundo valor da lista

int

## Caminhos = path

Fornece funções para trabalhar com caminhos de arquivo de forma independente de plataforma, permitindo manipular caminhos, como juntar partes de caminhos, verificar a existência de arquivos ou diretórios, obter o nome do arquivo ou diretório de um caminho e muito mais.

In [71]:
# Associando o caminho a variável path
path = r"C:\Users\bruna\OneDrive\Documentos\UFSC\Controle de Poluicao Atmosferica\ENS5173_20241"
print(path)

C:\Users\bruna\OneDrive\Documentos\UFSC\Controle de Poluicao Atmosferica\ENS5173_20241


"r" antes da string do caminho indica uma string de "raw", que trata os caracteres de escape, como barras invertidas, de forma literal. Isso é comum em caminhos de arquivos no Windows para evitar que os caracteres de escape sejam interpretados incorretamente.

In [72]:
path = "C:/Users/bruna/OneDrive/Documentos/UFSC/Controle de Poluicao Atmosferica/ENS5173_20241"
print(path)

C:/Users/bruna/OneDrive/Documentos/UFSC/Controle de Poluicao Atmosferica/ENS5173_20241


In [73]:
import os
# Listar arquivos na pasta
os.listdir(path)

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'Atividade01_Etapa01.ipynb',
 'Aula01.ipynb',
 'README.md',
 'scripts',
 'venv']

In [74]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [75]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:/Users/bruna/OneDrive/Documentos/UFSC/Controle de Poluicao Atmosferica/ENS5173_20241/.git'

Refere-se à operação de combinar partes de caminhos de diretórios em um único caminho completo.

In [76]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [77]:
# Diretório que estou trabalhando
os.getcwd()

'C:\\Users\\bruna\\OneDrive\\Documentos\\UFSC\\Controle de Poluicao Atmosferica'

In [78]:
# Mudo de diretório para o caminho
os.chdir('C:\\Users\\bruna\\OneDrive\\Documentos\\UFSC\\Controle de Poluicao Atmosferica\\')

In [79]:
os.getcwd() 

'C:\\Users\\bruna\\OneDrive\\Documentos\\UFSC\\Controle de Poluicao Atmosferica'

In [80]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('Diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Diretório já existe


if (se)\
else (senão)

In [81]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):  #verifica se a pasta existe
    print('Diretório já existe')
    # Criando arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("You text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("You text goes here")
    

Diretório já existe


"with" é usada em conjunto com o gerenciamento de contexto para garantir que recursos sejam adequadamente liberados após o término de sua utilização, independentemente de ocorrerem exceções ou não.

## Numpy arrays e Pandas DataFrames

NumPy Arrays são ideais para computação numérica eficiente e manipulação de arrays multidimensionais, enquanto Pandas DataFrames são excelentes para análise de dados tabulares e manipulação de conjuntos de dados de forma conveniente e eficiente.
Ambas as bibliotecas são amplamente utilizadas em ciência de dados, aprendizado de máquina, análise estatística e muitos outros campos relacionados ao processamento de dados em Python.

In [82]:
import numpy as np
# criando uma variável numpy e declarando como vou chama-la
n = np.array(0)
type(n)

numpy.ndarray

In [83]:
# criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [84]:
# criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# dimensões da matriz
print(n.shape)

[[7.87731051e-01 1.80830335e-01 1.43374384e-02 9.07198129e-01
  7.88667250e-01 2.17386037e-01 8.60361285e-01 5.91291137e-01
  8.84627814e-01 1.26575609e-01]
 [4.44979532e-01 8.37672965e-01 2.34947315e-01 5.70988723e-01
  1.44180186e-01 5.49979212e-01 3.48051954e-01 6.21046832e-01
  6.64770013e-01 2.70224275e-01]
 [8.46707973e-01 4.74252616e-01 1.18127004e-01 2.89056500e-01
  5.07073873e-01 2.78355327e-01 1.32082267e-01 6.12588338e-01
  3.18259471e-01 7.53130493e-01]
 [6.24515771e-01 7.11655863e-01 7.58556139e-01 4.37166181e-01
  7.50883422e-01 9.21297381e-01 9.89340608e-01 3.16304992e-01
  4.77942302e-02 3.57962866e-01]
 [8.84355401e-01 7.07136584e-01 4.45970803e-01 9.03420670e-01
  8.88829524e-02 4.86376494e-01 4.60849163e-01 5.42077532e-01
  4.02478714e-02 8.39763185e-01]
 [4.45528310e-01 8.54170972e-01 7.88365378e-01 5.47950372e-01
  4.75104991e-02 8.01839845e-01 3.02552798e-01 8.19799261e-01
  2.32594698e-01 6.84000037e-01]
 [4.88098314e-01 2.61679793e-01 7.58540474e-02 5.18832495e

In [85]:
# acessando valores da matriz
n[0,:]

array([0.78773105, 0.18083033, 0.01433744, 0.90719813, 0.78866725,
       0.21738604, 0.86036128, 0.59129114, 0.88462781, 0.12657561])

In [86]:
# primeiro número de todas as matrizes
n[:,0]

array([0.78773105, 0.44497953, 0.84670797, 0.62451577, 0.8843554 ,
       0.44552831, 0.48809831, 0.23502397, 0.71429216, 0.07852552])

In [87]:
# pegando o segundo até o quinto valor de todas as matrizes
n[:,1:5]

array([[0.18083033, 0.01433744, 0.90719813, 0.78866725],
       [0.83767297, 0.23494732, 0.57098872, 0.14418019],
       [0.47425262, 0.118127  , 0.2890565 , 0.50707387],
       [0.71165586, 0.75855614, 0.43716618, 0.75088342],
       [0.70713658, 0.4459708 , 0.90342067, 0.08888295],
       [0.85417097, 0.78836538, 0.54795037, 0.0475105 ],
       [0.26167979, 0.07585405, 0.5188325 , 0.79741036],
       [0.32650029, 0.82413772, 0.01546246, 0.09594933],
       [0.4711477 , 0.05506916, 0.68823328, 0.24508254],
       [0.10330415, 0.5619775 , 0.15550078, 0.24224229]])

In [88]:
# pegando o segundo até o quinto valor da primeira matriz
n[0,1:5]

array([0.18083033, 0.01433744, 0.90719813, 0.78866725])

In [89]:
# pegando o ultimo número da primeira matriz
n[0,-1]

0.1265756086953178

In [90]:
# pegando o quinto valor até o ultimo valor da primeira matriz
n[0,4:-1]

array([0.78866725, 0.21738604, 0.86036128, 0.59129114, 0.88462781])

In [91]:
# pegando o quinto valor até o final da primeira matriz
n[0,4:]

array([0.78866725, 0.21738604, 0.86036128, 0.59129114, 0.88462781,
       0.12657561])

In [92]:
an = np.log(n*5) # multipliquei todos os valores de n e fiz o logarítimo deles
print(an)

[[ 1.37083936 -0.10075815 -2.63544318  1.5120435   1.37202713  0.08335738
   1.45903503  1.08399115  1.48684964 -0.45747754]
 [ 0.79971092  1.4323104   0.16104393  1.04905209 -0.32725356  1.01156311
   0.55403439  1.13308913  1.20112377  0.3009349 ]
 [ 1.44303849  0.86342276 -0.52655701  0.3683048   0.93033933  0.33058109
  -0.4148924   1.11937579  0.46454963  1.32592114]
 [ 1.13865922  1.26927709  1.33309944  0.78199603  1.32293304  1.52746551
   1.5987213   0.45838954 -1.43141244  0.58211189]
 [ 1.48654165  1.26290647  0.80193612  1.50787094 -0.810997    0.88866564
   0.83475343  0.99709167 -1.60326025  1.43480256]
 [ 0.80094343  1.45181401  1.37164429  1.00786735 -1.43736665  1.38859153
   0.41393844  1.41074214  0.15098008  1.22964061]
 [ 0.89219948  0.26880423 -0.9695063   0.95326372  1.38305207 -0.45829471
   1.55541697  0.02246304  1.32994459 -0.1330476 ]
 [ 0.16137015  0.49011347  1.41602028 -2.55990197 -0.73449712  1.49284634
  -0.35642376  1.16715888  1.55030983 -0.67046368]
